### ISSUE TITLE
Dependency sucks

### ISSUE THREAD

**Issue by biexiang** [stathat/consistent#22]
First I cannot get your package when I turn on my proxy in http://www.stathat.com/c/consistent
It get 500 Error
if I turn off proxy , I can get your package，but I cannot get other important dependency 
I don't know why you put the import path not from github 
whatever it sucks

**Comment by pkumza** [comment]
I have the same question.

```bash
$ go mod why stathat.com/c/consistent
# stathat.com/c/consistent
code.byted.org/service_mesh/cp_cache/internal/cache
github.com/stathat/consistent
github.com/stathat/consistent.test
stathat.com/c/consistent
```
could you please move `example_test.go` to another directory?

**Comment by pkumza** [comment]
@patrickxb 
You didn't understand what I mean.
code.byted.org/xxx is my personal code. 
Have you used go module? Do you know what `go mod why` mean?
Because there's something wrong with stathat.com, I cannot use `stathat.com/c/consistent` in GO111MODULE, so I have to replace `stathat.com/c/consistent` with `github.com/stathat/consistent`, but github.com/stathat/consistent.test import `stathat.com/c/consistent`.

I DON'T WANT `github.com/stathat/consistent` RELIES ON `stathat.com/c/consistent`.
